database:
    pool-size: 16

swagger:
    protocol: https

logging:
    level:
        com.wutsi: INFO

koki:
    smtp:
        host: ${SMTP_HOST}
        port: ${SMTP_PORT}
        username: ${SMTP_USER}
        password: ${SMTP_PASSWORD}
        from: no-reply@wutsi.com

    module:
        consumer-delay-seconds: 60

wutsi:
    platform:
        cache:
            redis:
                url: ${REDISCLOUD_URL}
        storage:
            type: s3
            s3:
                bucket: com-wutsi-koki-prod
                region: us-east-1
                access-key: ${AWS_ACCESS_KEY}
                secret-key: ${AWS_SECRET_KEY}
        mq:
            type: rabbitmq
            rabbitmq:
                url: ${CLOUDAMQP_URL}
